resources:
- manager.yaml
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
images:
- name: controller
  newName: ghcr.io/oakestra/plugin-kubernetes/plugin-kubernetes/oakestra-controller-manager
  newTag: latest
