//go:build !ignore_autogenerated

/*
Copyright 2024 Jakob Kempter.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by controller-gen. DO NOT EDIT.

package v1

import (
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Instance) DeepCopyInto(out *Instance) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Instance.
func (in *Instance) DeepCopy() *Instance {
	if in == nil {
		return nil
	}
	out := new(Instance)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in InstanceNummberSet) DeepCopyInto(out *InstanceNummberSet) {
	{
		in := &in
		*out = make(InstanceNummberSet, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new InstanceNummberSet.
func (in InstanceNummberSet) DeepCopy() InstanceNummberSet {
	if in == nil {
		return nil
	}
	out := new(InstanceNummberSet)
	in.DeepCopyInto(out)
	return *out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *OakestraJob) DeepCopyInto(out *OakestraJob) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new OakestraJob.
func (in *OakestraJob) DeepCopy() *OakestraJob {
	if in == nil {
		return nil
	}
	out := new(OakestraJob)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *OakestraJob) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *OakestraJobList) DeepCopyInto(out *OakestraJobList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]OakestraJob, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new OakestraJobList.
func (in *OakestraJobList) DeepCopy() *OakestraJobList {
	if in == nil {
		return nil
	}
	out := new(OakestraJobList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *OakestraJobList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *OakestraJobSpec) DeepCopyInto(out *OakestraJobSpec) {
	*out = *in
	if in.AddedFiles != nil {
		in, out := &in.AddedFiles, &out.AddedFiles
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.Cmd != nil {
		in, out := &in.Cmd, &out.Cmd
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.InstanceList != nil {
		in, out := &in.InstanceList, &out.InstanceList
		*out = make([]Instance, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new OakestraJobSpec.
func (in *OakestraJobSpec) DeepCopy() *OakestraJobSpec {
	if in == nil {
		return nil
	}
	out := new(OakestraJobSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *OakestraJobStatus) DeepCopyInto(out *OakestraJobStatus) {
	*out = *in
	if in.InstanceList != nil {
		in, out := &in.InstanceList, &out.InstanceList
		*out = make(InstanceNummberSet, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new OakestraJobStatus.
func (in *OakestraJobStatus) DeepCopy() *OakestraJobStatus {
	if in == nil {
		return nil
	}
	out := new(OakestraJobStatus)
	in.DeepCopyInto(out)
	return out
}
